### ISSUE TITLE
Operating Systems list is outdated.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/software#16]
Hello,
I think the list of Operating Systems on this page is outdated.
https://cloud.ibm.com/docs/software?topic=software-about-software

- Debian 7 is no longer available.
- Windows 2019 is available.
- Ubuntu 18 is available.

Thanks,

**Comment by ytama** [comment]
Thank you for updating the page.
Now, we can select RHEL 8.  So could you update the page again?
Thanks!

**Comment by ytama** [comment]
I will point out one more.
Ubuntu 14 is no longer available.

**Comment by bpersich** [comment]
Updated with the last comment. This content is moving to the bare-metal repo. Please open future issues there. Thank you.
